# Feature 5: Containerize the build.  Create a container image with necessary dependencies to local and CI builds in a consistent and reproducible way, and use that container in CI. 
FROM node:20-bullseye

WORKDIR /app

RUN npm install -g electron-builder

COPY package.json package-lock.json ./
RUN npm install --production

COPY . .

CMD ["bash"]