# Feature 5: Containerize the build.  Create a container image with necessary dependencies to local and CI builds in a consistent and reproducible way, and use that container in CI. 
#Base image with Node.js 20 on Debian Bullseye
FROM node:20-bullseye 
# Set working directory, just standard workind dir
WORKDIR /app 

# Enable Yarn using Corepack (built into Node)
RUN corepack enable && corepack prepare yarn@stable --activate
# Now yarn is available
RUN yarn global add electron-builder

COPY package.json package-lock.json ./
RUN yarn install

# Copy the rest of the project into the image
COPY . .

CMD ["bash"]